CREATE DATABASE SIRMA_EXAM
GO

USE SIRMA_EXAM
GO

BEGIN TRANSACTION

CREATE TABLE tbl_Actors(
	ActorID INT PRIMARY KEY,
	FullName VARCHAR(100),
	BirthDate DATE
)

CREATE TABLE tbl_Movies(
	MovieID INT PRIMARY KEY,
	Title VARCHAR(100),
	ReleaseDate DATE
)

CREATE TABLE tbl_Roles(
	RoleID INT PRIMARY KEY,
	ActorID INT,
	MovieID INT,
	ROLENAME VARCHAR(100),

	FOREIGN KEY (ActorID)
	REFERENCES tbl_Actors(ActorID) ON DELETE CASCADE,

	FOREIGN KEY (MovieID)
	REFERENCES tbl_Movies(MovieID) ON DELETE CASCADE
)

COMMIT

